import type { Metadata } from "next";
import { Geist, Geist_Mono, Arimo, Kaushan_Script, VT323, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
// app/layout.tsx

// Configure your fonts
const arimo = Arimo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-arimo',
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
});

const kaushan = Kaushan_Script({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kaushan',
  weight: '400',
});

const vt323 = VT323({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-vt323',
  weight: '400',
});

const ibm = IBM_Plex_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ibm',
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "G-drive-scroller",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${arimo.variable} ${kaushan.variable} ${vt323.variable} ${ibm.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
